# Generated by Django 5.2.13 on 2026-04-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('event', models.CharField(blank=True, max_length=300)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('rank', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=300)),
                ('cgpa', models.CharField(blank=True, max_length=30)),
                ('start_year', models.CharField(max_length=10)),
                ('end_year', models.CharField(blank=True, max_length=10)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(blank=True, max_length=50)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(help_text='Bullet points separated by newlines')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(blank=True, max_length=50)),
                ('bullets', models.TextField(help_text='Activities separated by newlines')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Md Mursalatul Islam Pallob', max_length=200)),
                ('tagline', models.CharField(default='Software Engineer & AI/ML Researcher', max_length=300)),
                ('roles', models.CharField(default='Software Developer,AI/ML Researcher,Competitive Programmer', help_text='Comma-separated list of rotating roles for hero typewriter', max_length=500)),
                ('about_text', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('resume_file', models.FileField(blank=True, upload_to='resume/')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('years_experience', models.PositiveIntegerField(default=3)),
                ('cgpa', models.CharField(default='3.60/4.00', max_length=20)),
                ('achievements_count', models.PositiveIntegerField(default=12)),
                ('projects_count', models.PositiveIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tech_tags', models.CharField(help_text='Comma-separated tags', max_length=500)),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('date', models.CharField(blank=True, max_length=50)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-featured'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(max_length=500)),
                ('journal', models.CharField(blank=True, max_length=300)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('working', 'Working On'), ('published', 'Published'), ('preprint', 'Preprint')], default='working', max_length=20)),
                ('url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Languages', 'Languages'), ('Frameworks', 'Frameworks'), ('Tools', 'Developer Tools'), ('Libraries', 'Libraries'), ('Other', 'Other')], max_length=50)),
                ('proficiency', models.PositiveIntegerField(default=80, help_text='0-100 percentage')),
                ('icon', models.CharField(blank=True, help_text='devicon class e.g. devicon-python-plain', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
