# Generated by Django 5.2.13 on 2026-04-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_profile_photo_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('expert', 'Expert'), ('advanced', 'Advanced'), ('proficient', 'Proficient')], default='advanced', help_text='Proficiency level shown on the card', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='projects_text',
            field=models.TextField(blank=True, help_text='Real projects built with this skill — one per line'),
        ),
        migrations.AddField(
            model_name='skill',
            name='proof_statement',
            field=models.CharField(blank=True, help_text='One-line proof e.g. "Built ML pipeline processing 10M rows/day"', max_length=300),
        ),
        migrations.AddField(
            model_name='skill',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated quick-scan tags e.g. "OOP, scripting, data pipelines"', max_length=500),
        ),
        migrations.AddField(
            model_name='skill',
            name='techniques_text',
            field=models.TextField(blank=True, help_text='Specific techniques used — one per line'),
        ),
        migrations.AddField(
            model_name='skill',
            name='years',
            field=models.PositiveIntegerField(default=1, help_text='Years of experience with this technology'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.PositiveIntegerField(default=80, help_text='Legacy: 0-100 percentage (unused in UI)'),
        ),
    ]
