# Generated by Django 5.2.13 on 2026-04-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_skill_level_skill_projects_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='achievements_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='projects_count',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='projects_text',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='proof_statement',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='techniques_text',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='years',
        ),
        migrations.AddField(
            model_name='profile',
            name='cp_problems_authored',
            field=models.PositiveIntegerField(default=0, help_text='Number of CP problems authored (set manually)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cp_problems_solved',
            field=models.PositiveIntegerField(default=0, help_text='Number of CP problems solved (set manually)'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.PositiveIntegerField(default=80, help_text='0-100 percentage'),
        ),
    ]
