# Generated by Django 5.2.13 on 2026-04-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_profile_achievements_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_email_in_about',
            field=models.BooleanField(default=True, verbose_name="Show Email in 'Who Am I'"),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_email_in_contact',
            field=models.BooleanField(default=True, verbose_name="Show Email in 'Contact'"),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_facebook_in_about',
            field=models.BooleanField(default=True, verbose_name="Show Facebook in 'Who Am I'"),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_facebook_in_contact',
            field=models.BooleanField(default=True, verbose_name="Show Facebook in 'Contact'"),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_github_in_about',
            field=models.BooleanField(default=True, verbose_name="Show GitHub in 'Who Am I'"),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_github_in_contact',
            field=models.BooleanField(default=True, verbose_name="Show GitHub in 'Contact'"),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_linkedin_in_about',
            field=models.BooleanField(default=True, verbose_name="Show LinkedIn in 'Who Am I'"),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_linkedin_in_contact',
            field=models.BooleanField(default=True, verbose_name="Show LinkedIn in 'Contact'"),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_phone_in_about',
            field=models.BooleanField(default=True, verbose_name="Show Phone in 'Who Am I'"),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_phone_in_contact',
            field=models.BooleanField(default=True, verbose_name="Show Phone in 'Contact'"),
        ),
    ]
