# Generated by Django 5.2.13 on 2026-04-20 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_facebook_url_profile_show_email_in_about_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cgpa',
        ),
    ]
