# Generated by Django 5.2.13 on 2026-04-20 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_education_cgpa_remove_profile_cgpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
