# Generated by Django 5.2.13 on 2026-04-21 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
    ]
