# Generated by Django 5.2.13 on 2026-04-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_skill_proficiency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='Devicon class — see devicon.dev. E.g. devicon-python-plain. Note: DRF has no icon, use devicon-django-plain instead.', max_length=100),
        ),
    ]
