# Generated by Django 5.2.13 on 2026-04-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_project_date_alter_skill_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_font', models.CharField(choices=[('normal', 'Normal'), ('josefin', 'Josefin Sans'), ('teko', 'Teko')], default='josefin', max_length=50, verbose_name='Website Font')),
            ],
            options={
                'verbose_name': 'Website Setting',
                'verbose_name_plural': 'Website Settings',
            },
        ),
    ]
