# Generated by Django 5.2.9 on 2026-04-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_websitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hero_badge_1_color',
            field=models.CharField(default='#10B981', help_text='Hex color or CSS variable', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='hero_badge_1_text',
            field=models.CharField(default='AI/ML Research', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='hero_badge_2_color',
            field=models.CharField(default='var(--accent-blue)', help_text='Hex color or CSS variable', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='hero_badge_2_text',
            field=models.CharField(default='Django Expert', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='hero_badge_3_color',
            field=models.CharField(default='#F59E0B', help_text='Hex color or CSS variable', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='hero_badge_3_text',
            field=models.CharField(default='ICPC Contestant', max_length=50),
        ),
    ]
