# Generated by Django 5.2.9 on 2026-04-22 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_profile_hero_badge_1_color_profile_hero_badge_1_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hero_badge_1_color',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hero_badge_1_text',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hero_badge_2_color',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hero_badge_2_text',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hero_badge_3_color',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hero_badge_3_text',
        ),
        migrations.CreateModel(
            name='HeroBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('color', models.CharField(default='#10B981', help_text='Hex color or CSS variable', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_badges', to='core.profile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
