# Generated by Django 5.2.9 on 2026-05-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_profile_hero_badge_1_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentlyWorkingOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Short descriptor, e.g. "ML Research Paper"', max_length=300)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('research', 'Research'), ('project', 'Project'), ('learning', 'Learning'), ('competition', 'Competition'), ('other', 'Other')], default='project', max_length=30)),
                ('progress', models.PositiveIntegerField(default=0, help_text='Progress percentage 0-100')),
                ('link_url', models.URLField(blank=True, help_text='Optional link (GitHub, paper, etc.)')),
                ('link_label', models.CharField(blank=True, help_text='Link button label, e.g. "View on GitHub"', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Show this item on the portfolio')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Currently Working On',
                'verbose_name_plural': 'Currently Working On',
                'ordering': ['order'],
            },
        ),
    ]
