# Generated by Django 5.2.13 on 2026-07-20 19:37

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_analyticsmetric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resume_file',
            field=models.FileField(blank=True, storage=core.models.OverwriteStorage(), upload_to=core.models.get_resume_upload_path),
        ),
    ]
